---

#
# This file is part of the `src-run/srw-app` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this vinylSourceStream code.
#

#
# perforce file resource imports
#

imports:
  - { resource: parameters.yml }
  - { resource: platform.php }
  - { resource: security.yml }
  - { resource: services.yml }

#
# container parameters
#

parameters:
  locale: en

  srw_app.domain: "src.run"

  srw_app.path.root.sys: "%kernel.root_dir%/../web/"
  srw_app.path.root.web: /
  srw_app.path.frontend_assets.web: "/bundles/frontend/"

  srw_app.assets.javascriptpackage: javascripts
  srw_app.assets.javascript.dev: app.js
  srw_app.assets.javascript.prod: app.min.js
  srw_app.assets.stylesheets.package: stylesheets
  srw_app.assets.stylesheets.dev: app.css
  srw_app.assets.stylesheets.prod: app.min.css

#
# general framework
#

framework:

  secret: "%secret%"

  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~

  form:            ~
  csrf_protection: ~
  validation:
    enable_annotations: true

  serializer:
    enable_annotations: true

  templating:
    engines: [ 'twig' ]

  default_locale:  "%locale%"

  trusted_hosts:   ~
  trusted_proxies: ~

  session:
    handler_id:  session.handler.native_file
    save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"

  fragments: ~

  http_method_override: true

  assets:
    enabled: true
    version: 0.1.0
    version_format: "%%s?v=%%s"
    packages:
      images:
        base_urls:
          - "//%srw_app.domain%%srw_app.path.frontend_assets.web%images/"
      stylesheets:
        base_path: "%srw_app.path.frontend_assets.web%stylesheets/"
      javascripts:
        base_path: "%srw_app.path.frontend_assets.web%javascripts/"

#
# templating
#

twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"

#
# asset management
#

assetic :
  debug: '%kernel.debug%'
  use_controller: false

  bundles:
    - FrontendBundle

#
# database
#

doctrine:

  dbal :

    server_version: "%database_version%"
    driver: "%database_driver%"
    host: "%database_host%"
    port: "%database_port%"
    dbname: "%database_name%"
    user: "%database_user%"
    password: "%database_password%"
    charset: "%database_charset%"

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

#
# email transport
#

swiftmailer:
  transport: "%mailer_transport%"
  host: "%mailer_host%"
  port: "%mailer_port%"
  username: "%mailer_user%"
  password: "%mailer_password%"
  spool:
    type: "%mailer_spool%"

#
# mail spooler
#

white_october_swift_mailer_db :
  entity_class: SR\WebApp\BackendBundle\Entity\Email
  keep_sent_messages: true
