---

#
# This file is part of the `src-run/srw-app` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this vinylSourceStream code.
#

#
# perforce file resource imports
#

imports :
  - { resource: config.yml }
  - { resource: bundles_dev.yml }


#
# main framework config
#

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler:
    only_exceptions: false


#
# web profiler config
#

web_profiler:
  toolbar: true
  intercept_redirects: false


#
# logger config
#

monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
    firephp:
      type: firephp
      level: info
    chromephp:
      type: chromephp
      level: info


#
# asset cofig
#

assetic:
  use_controller: true


#
# doctrine config
#

doctrine:
  orm:
    metadata_cache_driver: array
    result_cache_driver: array
    query_cache_driver: array


#
# doctrine migrations config
#

doctrine_migrations :
  dir_name: "%kernel.root_dir%/Resources/migrations"
  namespace: SR\App\BackendBundle\Migrations
  table_name: migration_versions
  name: srw-app
